import React from 'react';
import { Text, View } from 'react-native';
import PrimaryButton from '../components/PrimaryButton';
import { useAuth } from '../context/AuthContext';

export default function HomeScreen() {
    const { logout } = useAuth();

    return (
        <View className="flex-1 items-center justify-center bg-white px-6">
            <Text className="text-2xl font-bold text-gray-900">__PROJECT_NAME__</Text>
            <Text className="mt-2 text-center text-base text-gray-600">
                Generated by DevStarter – React Native (Expo) starter
            </Text>

            <View className="mt-8 w-full">
                <PrimaryButton title="Logout" onPress={logout} />
            </View>
        </View>
    );
}
