import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import PrimaryButton from '../components/PrimaryButton';

export default function HomeScreen() {
    return (
        <View style={styles.container}>
            <Text style={styles.title}>__PROJECT_NAME__</Text>
            <Text style={styles.subtitle}>Generated by DevStarter – React Native stack</Text>

            <PrimaryButton
                onPress={() => alert('Hello!')}
                title="Get Started"
            />
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 10
    },
    subtitle: {
        fontSize: 16,
        color: '#666',
        marginBottom: 30
    }
});
